'use client';

import { useEffect, useMemo, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { ArrowDownToLine, ArrowLeft, Check, ChevronDown, ChevronUp, ExternalLink, LogOut, Menu, Plus, Save, Trash2, Upload, X } from 'lucide-react';
import { clientApi, publicApiOrigin } from '@/lib/api';

const resources = ['products','scents','pages','rewards','faqs'];
const tabs = [['overview','Overview'],['products','Products'],['scents','Scents'],['pages','Pages'],['rewards','Rewards'],['faqs','FAQ'],['settings','Brand & launch'],['submissions','Messages'],['subscribers','Subscribers']];
const defaults = {
  products:{name:'',slug:'',kind:'',summary:'',body:'',scent:'',images:[],status:'draft',seo:{title:'',description:''}},
  scents:{name:'',slug:'',summary:'',body:'',images:[],status:'draft',seo:{title:'',description:''}},
  pages:{key:'',slug:'',title:'',eyebrow:'',intro:'',body:'',sections:[],images:[],status:'draft',seo:{title:'',description:''}},
  rewards:{title:'',slug:'',summary:'',body:'',order:0,status:'draft',seo:{title:'',description:''}},
  faqs:{question:'',answer:'',order:0,status:'draft'},
};
const labels = {products:'Product',scents:'Scent',pages:'Page',rewards:'Reward',faqs:'FAQ'};
const clone = object => JSON.parse(JSON.stringify(object));
const slugify = value => String(value || '').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const titleOf = (item,resource) => item?.name || item?.title || item?.question || (resource === 'submissions' ? item?.name || item?.email : item?.email) || 'Untitled';

function Field({ label, value, onChange, type='text', required=false, hint, rows=5, options, maxLength, disabled=false }) {
  return <label className="admin-field"><span>{label}</span>{options ? <select value={value ?? ''} onChange={e=>onChange(e.target.value)} required={required} disabled={disabled}>{options.map(([val,name])=><option key={val} value={val}>{name}</option>)}</select> : type==='textarea' ? <textarea rows={rows} value={value ?? ''} onChange={e=>onChange(e.target.value)} maxLength={maxLength} required={required} disabled={disabled} /> : <input type={type} value={value ?? ''} onChange={e=>onChange(e.target.value)} maxLength={maxLength} required={required} disabled={disabled} />}{hint&&<small>{hint}</small>}</label>;
}

function MediaManager({ label, images=[], onChange, single=false }) {
  const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  const list = single ? (images?.url ? [images] : []) : (Array.isArray(images) ? images : []);
  function update(next){onChange(single ? next[0] || null : next.map((item,i)=>({...item,order:i})))}
  async function upload(event){const file=event.target.files?.[0];if(!file)return;setBusy(true);setError('');try{if(file.size>6*1024*1024)throw new Error('Use an image under 6 MB.');const result=await clientApi('/admin/media',{method:'POST',body:(()=>{const data=new FormData();data.append('file',file);return data})()});const item=result.item||result;update(single?[item]:[...list,{...item,alt:'',caption:'',order:list.length}]);}catch(e){setError(e.message)}finally{setBusy(false);event.target.value=''}}
  return <div className="admin-media"><div className="admin-media-heading"><strong>{label}</strong><label className="admin-upload"><Upload size={15} /> {busy?'Uploading…':`Upload ${single?'image':'image'}`}<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={upload} disabled={busy} /></label></div>{error&&<p className="admin-error" role="alert">{error}</p>}{list.length===0&&<p className="admin-muted">No image selected. The public layout will use text.</p>}{list.map((image,index)=><div className="admin-media-item" key={`${image.publicId||image.url}-${index}`}><div className="admin-thumb">{/* Uploaded images are served by Cloudinary. */}<img src={image.url} alt={image.alt || 'Uploaded preview'} /></div><div className="admin-media-fields"><Field label="Alt text" value={image.alt} onChange={value=>update(list.map((entry,i)=>i===index?{...entry,alt:value}:entry))} hint="Describe the image for someone who cannot see it." /><Field label="Caption" value={image.caption} onChange={value=>update(list.map((entry,i)=>i===index?{...entry,caption:value}:entry))} /></div><div className="admin-media-actions">{!single&&<><button type="button" aria-label="Move image up" disabled={index===0} onClick={()=>{const next=[...list];[next[index-1],next[index]]=[next[index],next[index-1]];update(next)}}><ChevronUp size={16}/></button><button type="button" aria-label="Move image down" disabled={index===list.length-1} onClick={()=>{const next=[...list];[next[index+1],next[index]]=[next[index],next[index+1]];update(next)}}><ChevronDown size={16}/></button></>}<button type="button" aria-label="Remove image from record" onClick={()=>update(list.filter((_,i)=>i!==index))}><X size={16}/></button></div></div>)}</div>;
}

function RecordEditor({ resource, item, scents, onSave, onDelete, onCancel, busy }) {
  const [draft,setDraft]=useState(clone(item));
  useEffect(()=>setDraft(clone(item)),[item]);
  const set=(key,value)=>setDraft(previous=>({...previous,[key]:value}));
  const updateName=(key,value)=>setDraft(previous=>({...previous,[key]:value,slug:!previous._id && (!previous.slug || previous.slug===slugify(previous[key])) ? slugify(value) : previous.slug}));
  const hasSeo=resource!=='faqs';
  return <form className="admin-editor" onSubmit={e=>{e.preventDefault();onSave(draft)}}><div className="admin-editor-head"><div><span className="eyebrow">{item._id?'Edit':'New'} {labels[resource]}</span><h2>{titleOf(draft,resource)}</h2></div><button type="button" className="admin-icon-button" onClick={onCancel} aria-label="Close editor"><X size={19}/></button></div>
    {resource==='products'&&<><div className="admin-two"><Field label="Name" value={draft.name} onChange={v=>updateName('name',v)} required /><Field label="Slug" value={draft.slug} onChange={v=>set('slug',slugify(v))} required /></div><div className="admin-two"><Field label="Product type" value={draft.kind} onChange={v=>set('kind',v)} hint="For example: shampoo or body wash." required /><Field label="Scent" value={draft.scent?._id||draft.scent||''} onChange={v=>set('scent',v)} options={[[ '', 'Select a scent' ],...scents.map(s=>[s._id,s.name])]} required /></div><Field label="Short summary" value={draft.summary} onChange={v=>set('summary',v)} type="textarea" rows={3} /><Field label="Body" value={draft.body} onChange={v=>set('body',v)} type="textarea" rows={8} /><MediaManager label="Product images & gallery" images={draft.images} onChange={v=>set('images',v)} /></>}
    {resource==='scents'&&<><div className="admin-two"><Field label="Name" value={draft.name} onChange={v=>updateName('name',v)} required /><Field label="Slug" value={draft.slug} onChange={v=>set('slug',slugify(v))} required /></div><Field label="Short summary" value={draft.summary} onChange={v=>set('summary',v)} type="textarea" rows={3} /><Field label="Body" value={draft.body} onChange={v=>set('body',v)} type="textarea" rows={8} /><MediaManager label="Scent images & gallery" images={draft.images} onChange={v=>set('images',v)} /></>}
    {resource==='pages'&&<>
      <div className="admin-two"><Field label="Page key" value={draft.key} onChange={v=>set('key',v)} disabled hint="Fixed route identifier" /><Field label="URL path" value={draft.slug} onChange={v=>set('slug',v)} disabled hint="The site renders this path" /></div>
      <Field label="Title" value={draft.title} onChange={v=>set('title',v)} required />
      <Field label="Eyebrow" value={draft.eyebrow} onChange={v=>set('eyebrow',v)} />
      <Field label="Introduction" value={draft.intro} onChange={v=>set('intro',v)} type="textarea" rows={3} />
      <Field label="Body" value={draft.body} onChange={v=>set('body',v)} type="textarea" rows={8} />
      <div className="admin-subhead"><h3>Additional sections</h3><button type="button" className="admin-small-button" onClick={()=>set('sections',[...(draft.sections||[]),{heading:'',body:''}])}><Plus size={14}/> Add section</button></div>
      {(draft.sections||[]).map((section,i)=><div className="admin-section-field" key={i}><Field label="Heading" value={section.heading} onChange={v=>set('sections',draft.sections.map((s,j)=>i===j?{...s,heading:v}:s))} /><Field label="Body" value={section.body} onChange={v=>set('sections',draft.sections.map((s,j)=>i===j?{...s,body:v}:s))} type="textarea" rows={4} /><button type="button" className="admin-small-button" onClick={()=>set('sections',draft.sections.filter((_,j)=>i!==j))}>Remove section</button></div>)}
      <MediaManager label="Page gallery" images={draft.images} onChange={v=>set('images',v)} />
    </>}
    {resource==='rewards'&&<><div className="admin-two"><Field label="Title" value={draft.title} onChange={v=>updateName('title',v)} required /><Field label="Slug" value={draft.slug} onChange={v=>set('slug',slugify(v))} required /></div><Field label="Summary" value={draft.summary} onChange={v=>set('summary',v)} type="textarea" rows={3} /><Field label="Details" value={draft.body} onChange={v=>set('body',v)} type="textarea" rows={6} /><Field label="Display order" value={draft.order} onChange={v=>set('order',Number(v))} type="number" /></>}
    {resource==='faqs'&&<><Field label="Question" value={draft.question} onChange={v=>set('question',v)} required /><Field label="Answer" value={draft.answer} onChange={v=>set('answer',v)} type="textarea" rows={6} required /><Field label="Display order" value={draft.order} onChange={v=>set('order',Number(v))} type="number" /></>}
    {hasSeo&&<div className="admin-seo"><h3>Search appearance</h3><Field label="SEO title" value={draft.seo?.title} onChange={v=>set('seo',{...draft.seo,title:v})} /><Field label="SEO description" value={draft.seo?.description} onChange={v=>set('seo',{...draft.seo,description:v})} type="textarea" rows={3} /></div>}
    <div className="admin-editor-actions"><Field label="Visibility" value={draft.status} onChange={v=>set('status',v)} options={[[ 'draft','Draft' ],[ 'published','Published' ]]} /><button className="button button-gold" disabled={busy}><Save size={15}/>{busy?'Saving…':'Save changes'}</button>{item._id&&resource!=='pages'&&<button type="button" className="admin-danger-button" disabled={busy} onClick={()=>onDelete(item)}><Trash2 size={15}/> Delete</button>}</div>
  </form>;
}

function SettingsEditor({ item, onSave, busy }) {
  const [draft,setDraft]=useState(clone(item||{})); useEffect(()=>setDraft(clone(item||{})),[item]); const set=(key,value)=>setDraft(prev=>({...prev,[key]:value}));
  return <form className="admin-editor" onSubmit={e=>{e.preventDefault();onSave(draft)}}><div className="admin-editor-head"><div><span className="eyebrow">Site settings</span><h2>Brand & launch</h2></div></div><Field label="Brand name" value={draft.brandName} onChange={v=>set('brandName',v)} /><Field label="Tagline" value={draft.tagline} onChange={v=>set('tagline',v)} /><div className="admin-two"><Field label="Kickstarter launch date" value={draft.kickstarterLaunchDate?.slice(0,10)} onChange={v=>set('kickstarterLaunchDate',v)} type="date" /><Field label="Kickstarter URL" value={draft.kickstarterUrl} onChange={v=>set('kickstarterUrl',v)} type="url" /></div><Field label="Canonical site URL" value={draft.canonicalUrl} onChange={v=>set('canonicalUrl',v)} type="url" hint="Leave blank until a production domain is connected. Sitemap and indexing stay disabled." /><MediaManager label="Brand logo" images={draft.logo} onChange={v=>set('logo',v)} single /><MediaManager label="Favicon" images={draft.favicon} onChange={v=>set('favicon',v)} single /><MediaManager label="Homepage artwork" images={draft.homeImage} onChange={v=>set('homeImage',v)} single /><div className="admin-editor-actions"><button className="button button-gold" disabled={busy}><Save size={15}/>{busy?'Saving…':'Save settings'}</button></div></form>;
}

export default function AdminDashboard() {
  const router=useRouter(); const search=useSearchParams(); const active=tabs.some(([key])=>key===search.get('tab'))?search.get('tab'):'overview';
  const [user,setUser]=useState(null); const [loading,setLoading]=useState(true); const [records,setRecords]=useState({}); const [settings,setSettings]=useState({}); const [selected,setSelected]=useState(null); const [busy,setBusy]=useState(false); const [message,setMessage]=useState({type:'',text:''}); const [menuOpen,setMenuOpen]=useState(false);
  useEffect(()=>{if(!menuOpen)return;const close=event=>{if(event.key==='Escape')setMenuOpen(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[menuOpen]);
  useEffect(()=>{let live=true;(async()=>{try{const me=await clientApi('/admin/me');if(!live)return;setUser(me.user||me);const results=await Promise.allSettled([...resources.map(r=>clientApi(`/admin/${r}`)),clientApi('/admin/settings'),clientApi('/admin/submissions'),clientApi('/admin/subscribers')]);if(!live)return;const next={};resources.forEach((r,i)=>next[r]=results[i].status==='fulfilled'?(results[i].value.items||[]):[]);next.submissions=results[6].status==='fulfilled'?(results[6].value.items||[]):[];next.subscribers=results[7].status==='fulfilled'?(results[7].value.items||[]):[];setRecords(next);if(results[5].status==='fulfilled')setSettings(results[5].value.item||results[5].value);const failed=results.filter(r=>r.status==='rejected');if(failed.length)setMessage({type:'error',text:`${failed.length} admin section${failed.length>1?'s':''} could not load. Refresh to retry.`});}catch{router.replace('/admin/login')}finally{if(live)setLoading(false)}})();return()=>{live=false}},[router]);
  function switchTab(tab){setSelected(null);setMessage({type:'',text:''});setMenuOpen(false);router.push(`/admin${tab==='overview'?'':`?tab=${tab}`}`)}
  async function reload(resource){const result=await clientApi(`/admin/${resource}`);setRecords(prev=>({...prev,[resource]:result.items||[]}))}
  async function saveRecord(draft){setBusy(true);setMessage({type:'',text:''});try{const { _id,createdAt,updatedAt,__v,...payload}=draft;await clientApi(`/admin/${active}${_id?`/${_id}`:''}`,{method:_id?'PATCH':'POST',body:payload});await reload(active);setSelected(null);setMessage({type:'success',text:`${labels[active]} saved.`})}catch(e){setMessage({type:'error',text:e.message})}finally{setBusy(false)}}
  async function deleteRecord(item){if(!window.confirm(`Delete “${titleOf(item,active)}”? This removes the record from the site.`))return;setBusy(true);setMessage({type:'',text:''});try{await clientApi(`/admin/${active}/${item._id}`,{method:'DELETE'});await reload(active);setSelected(null);setMessage({type:'success',text:`${labels[active]} deleted.`})}catch(e){setMessage({type:'error',text:e.message})}finally{setBusy(false)}}
  async function saveSettings(draft){setBusy(true);setMessage({type:'',text:''});try{const result=await clientApi('/admin/settings',{method:'PATCH',body:draft});setSettings(result.item||result);setMessage({type:'success',text:'Settings saved. Published pages will use the new details.'})}catch(e){setMessage({type:'error',text:e.message})}finally{setBusy(false)}}
  async function updateRecord(resource,item,patch){setBusy(true);setMessage({type:'',text:''});try{await clientApi(`/admin/${resource}/${item._id}`,{method:'PATCH',body:patch});await reload(resource);setMessage({type:'success',text:'Status updated.'})}catch(e){setMessage({type:'error',text:e.message})}finally{setBusy(false)}}
  async function downloadCsv(){setBusy(true);setMessage({type:'',text:''});try{const response=await fetch(`${publicApiOrigin}/api/admin/subscribers.csv`,{credentials:'include'});if(!response.ok)throw new Error('Could not export subscribers.');const url=URL.createObjectURL(await response.blob());const anchor=document.createElement('a');anchor.href=url;anchor.download='dagger-and-bone-subscribers.csv';anchor.click();URL.revokeObjectURL(url)}catch(e){setMessage({type:'error',text:e.message})}finally{setBusy(false)}}
  async function logout(){try{await clientApi('/admin/logout',{method:'POST'})}finally{router.replace('/admin/login');router.refresh()}}
  const counts=useMemo(()=>Object.fromEntries([...resources,'submissions','subscribers'].map(r=>[r,(records[r]||[]).length])),[records]);
  if(loading)return <div className="admin-loading">Loading dashboard…</div>;
  if(!user)return null;
  return <div className="admin-layout"><aside className={`admin-sidebar ${menuOpen?'open':''}`}><div className="admin-brand"><button type="button" className="admin-drawer-close" aria-label="Close admin menu" onClick={()=>setMenuOpen(false)}><X size={20}/></button><strong>Dagger <span>&</span> Bone</strong><small>Site admin</small></div><nav aria-label="Admin sections">{tabs.map(([key,label])=><button key={key} type="button" className={active===key?'active':''} onClick={()=>switchTab(key)}>{label}{counts[key]!=null&&<span>{counts[key]}</span>}</button>)}</nav><div className="admin-sidebar-bottom"><Link href="/" target="_blank" rel="noopener noreferrer">View site <ExternalLink size={14}/></Link><button type="button" onClick={logout}>Sign out <LogOut size={14}/></button></div></aside><div className="admin-main"><div className="admin-topbar"><button type="button" className="admin-menu-button" onClick={()=>setMenuOpen(!menuOpen)} aria-label={menuOpen?'Close admin menu':'Open admin menu'} aria-expanded={menuOpen}>{menuOpen?<X/>:<Menu/>}</button><span>Site dashboard</span><span>{user.email}</span></div><div className="admin-content">{message.text&&<p className={`admin-notice ${message.type}`} role="status">{message.text}<button onClick={()=>setMessage({type:'',text:''})} aria-label="Dismiss notice"><X size={15}/></button></p>}
      {active==='overview'&&<><div className="admin-page-heading"><span className="eyebrow">Welcome back</span><h1>Content overview</h1><p>Manage the pages, concepts, campaign, and messages that power the public site.</p></div><div className="admin-overview-grid">{tabs.slice(1).map(([key,label])=><button type="button" key={key} onClick={()=>switchTab(key)}><span>{label}</span><strong>{counts[key]??'→'}</strong><small>Open section ↗</small></button>)}</div><div className="admin-help"><h2>Publishing flow</h2><p>Save content as a draft while it is in progress. Published products, scents, pages, rewards, and answers appear through the public API. Upload images here, add meaningful alt text, then save the record to use them on the site.</p></div></>}
      {resources.includes(active)&&<><div className="admin-page-heading"><span className="eyebrow">Content</span><h1>{tabs.find(([key])=>key===active)?.[1]}</h1><p>{active==='products'?'Manage concepts and connect them to scents.':active==='scents'?'Add scents and their product relationships.':active==='pages'?'Edit published page copy, sections, and SEO.':active==='rewards'?'Keep founding rewards accurate and current.':'Publish clear answers to common questions.'}</p></div>{selected ? <><button className="admin-back" type="button" onClick={()=>setSelected(null)}><ArrowLeft size={16}/> Back to list</button><RecordEditor key={selected._id||`new-${active}`} resource={active} item={selected} scents={records.scents||[]} onSave={saveRecord} onDelete={deleteRecord} onCancel={()=>setSelected(null)} busy={busy} /></> : <><div className="admin-list-head"><span>{(records[active]||[]).length} records</span>{active!=='pages'&&<button className="button button-gold" onClick={()=>setSelected(clone(defaults[active]))}><Plus size={16}/> Add {labels[active]}</button>}</div><div className="admin-list">{(records[active]||[]).map(item=><button type="button" className="admin-list-row" key={item._id} onClick={()=>setSelected(item)}><span><strong>{titleOf(item,active)}</strong><small>{item.slug?(active==='pages'?item.slug:`/${item.slug}`):item.key||''}</small></span><span className={`admin-status ${item.status}`}>{item.status}</span><span aria-hidden="true">↗</span></button>)}{!(records[active]||[]).length&&<p className="admin-muted">{active==='pages'?'No page records found. Run the backend seed command.':'No records yet. Add the first one above.'}</p>}</div></>}</>}
      {active==='settings'&&<SettingsEditor item={settings} onSave={saveSettings} busy={busy} />}
      {active==='submissions'&&<><div className="admin-page-heading"><span className="eyebrow">Inbox</span><h1>Messages</h1><p>Contact form submissions are stored here even if email delivery fails.</p></div><div className="admin-list">{(records.submissions||[]).map(item=><article className="admin-message" key={item._id}><div><span className="eyebrow">{item.createdAt?new Date(item.createdAt).toLocaleString():''}</span><h2>{item.name}</h2><a href={`mailto:${item.email}`}>{item.email}</a><p>{item.message}</p></div><div className="admin-message-actions"><label>Status <select value={item.status||'new'} onChange={e=>updateRecord('submissions',item,{status:e.target.value})} disabled={busy}><option value="new">New</option><option value="read">Read</option><option value="handled">Handled</option></select></label></div></article>)}{!(records.submissions||[]).length&&<p className="admin-muted">No messages yet.</p>}</div></>}
      {active==='subscribers'&&<><div className="admin-page-heading"><span className="eyebrow">Email updates</span><h1>Subscribers</h1><p>View consent and subscription state. CSV export is available for your records.</p></div><div className="admin-list-head"><span>{(records.subscribers||[]).length} records</span><button className="button button-gold" type="button" onClick={downloadCsv} disabled={busy}><ArrowDownToLine size={16}/> Export CSV</button></div><div className="admin-list">{(records.subscribers||[]).map(item=><div className="admin-subscriber-row" key={item._id}><div><strong>{item.email}</strong><small>Consent: {item.consentAt?new Date(item.consentAt).toLocaleString():'Not recorded'}</small></div><span className={`admin-status ${item.status}`}>{item.status||'unknown'}</span>{item.status==='subscribed'&&<button type="button" className="admin-small-button" disabled={busy} onClick={()=>updateRecord('subscribers',item,{status:'unsubscribed'})}>Unsubscribe</button>}{['pending','integration_error'].includes(item.status)&&<button type="button" className="admin-small-button" disabled={busy} onClick={()=>updateRecord('subscribers',item,{status:'subscribed'})}>Retry subscription</button>}{['unsubscribed','unsubscribe_pending'].includes(item.status)&&<small>Fresh consent is required to rejoin.</small>}</div>)}{!(records.subscribers||[]).length&&<p className="admin-muted">No subscribers yet.</p>}</div></>}
    </div></div></div>;
}
